name: BetterBroadcast
version: 2.2.1
main: pe.nn.connor.betterbroadcast.PluginMain
website: http://www.connor.nn.pe/plugins/bb
commands:
    bb:
        description: The base BB command
        usage: /<command> <message>
    bbtoggle:
        description: Toggle the [BB] tag showing up
        usage: /<command>
    bbcolours:
        description: Shows you the Minecraft Colour Codes
        usage: /<command>
        aliases: bbcolors
    bbreload:
        description: Reloads the config
        usage: /<command>
