name: BetterBroadcast
version: 2.4
main: pe.nn.connor.betterbroadcast.PluginMain
website: http://www.connor.nn.pe/plugins/bb
commands:
    bb:
        description: The base BB command
        usage: /<command> <message>
    bbtoggle:
        description: Toggle the [BB] tag showing up
        usage: /<command>
    bbcolours:
        description: Shows you the Minecraft Colour Codes
        usage: /<command>
        aliases: bbcolors
    bbreload:
        description: Reloads the config
        usage: /<command>
    bbinfo:
        description: Displays information about the plugin
        usage: /<command>
    bbconfig:
        description: Controls the config from within Minecraft
        usage: See /<command> for help
